---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 0
      restartPolicy: Always
      containers:
        - name: jenkins
          imagePullPolicy: IfNotPresent
          image: jenkins/jenkins:2.204.2
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - mountPath: "/var/jenkins_home"
              name: jenkins-volume
      volumes:
        - name: jenkins-volume
          persistentVolumeClaim:
            claimName: jenkins-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    run: jenkins-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jenkins