---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:3.22.1-02
          securityContext:
            runAsUser: 0
          resources:
            limits:
              memory: "4Gi"
              cpu: "4000m"
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-data
              mountPath: "/nexus-data"
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-claim

---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  labels:
    app: nexus
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: nexus